pipeline:
  build:
    image: node:bullseye-slim
    commands:
      - npm install
      - npm run build
  publish:
    image: appleboy/drone-ssh
    settings:
      host:
        - projectsegfau.lt 
      username: $USERNAME
      key:
        from_secret: $KEY
      port: 6665 
      command_timeout: 1m
      script:
        - cd $${RPATH}
        - git pull
