pipeline:
  build:
    image: node:bullseye-slim
    commands:
      - npm install
      - npm run build
  publish:
    image: appleboy/drone-ssh
    settings:
      host:
        - $HOST
      username: $USERNAME
      key:
        from_secret: $KEY
      port: $PORT
      command_timeout: 1m
      script:
        - cd $RPATH
        - git pull
