pipeline:
  build:
    image: node:bullseye-slim
    commands:
      - npm install
      - npm run build
      - pwd
      - mv build/ ../
      - rm -rf *
      - mv ../build/* .
  push:
    image: appleboy/drone-git-push
    settings:
      branch: build
      remote: git@git.projectsegfau.lt:ProjectSegfault/website.git 
      force: true
      commit: true
      commit_message : Successfully built the page.
      ssh_key:
        from_secret: ssh_key_git
      
  update:
    image: appleboy/drone-ssh
    settings:
      host:
        - projectsegfau.lt 
      username: ${USERNAME}
      key:
       from_secret: ssh_key 
      port: 6665 
      command_timeout: 1m
      script:
        - cd /var/www/html
        - git pull
