services:
    website:
        container_name: website
        #image: realprojectsegfault/website
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          AUTH_SECRET: ${AUTH_SECRET}
        ports:
            - 1337:4173
        volumes:
            - ./config:/app/config
    website-db:
        image: postgres
        container_name: website-db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          PGDATA: /data/postgres
          POSTGRES_DB: website
        volumes:
          - website-db-data:/data/postgres
        ports:
          - "5432:5432"
        restart: unless-stopped

volumes:
    website-db-data: