services:
    website:
        container_name: website
        #image: realprojectsegfault/website:latest
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1339:4173
        environment:
          AUTH_SECRET: ${AUTH_SECRET}
          AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
          AUTH_URL: ${AUTH_URL}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
          DB_USERNAME: ${DB_USERNAME}
          DB_PASSWORD: ${DB_PASSWORD}
          AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
          AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
          AUTH_ISSUER: ${AUTH_ISSUER}
          HCAPTCHA_SECRET: ${HCAPTCHA_SECRET}
          HCAPTCHA_SITEKEY: ${HCAPTCHA_SITEKEY}
          WEBHOOK: ${WEBHOOK}

    website-db-dev:
        image: postgres
        container_name: website-db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          PGDATA: /data/postgres
          POSTGRES_DB: website
        volumes:
          - website-db-data:/data/postgres

        restart: unless-stopped

volumes:
    website-db-data: