db:
    url: "postgres://user:password@host:5432/database"

app:
    auth:
        clientId: "authentik-client-id"
        clientSecret: "authentik-client-secret"
        issuer: "https://yourdomain.com/application/o/app-name/"
    hcaptcha:
        secret: "your-hcaptcha-secret"
        sitekey: "your-hcaptcha-sitekey"
    webhook: "your-discord-webhook-url"